### ISSUE TITLE
Show latest logs in UI dashboard

### ISSUE THREAD

**Issue by KiraLT** [KiraLT/torrent-stream-server#263]
It's useful to easily check the latest logs. So in the UI dashboard, we can show the latest 100 log entries.

### TODO

- [x] Store the latest 100 logs in the memory with the ability to configure the limit
- [x] Create new API to retrieve logs
- [ ] Show logs in UI dashboard (maybe add a button with popup)
