### ISSUE TITLE
Torrent search rework

### ISSUE THREAD

**Issue by KiraLT** [KiraLT/torrent-stream-server#265]
### Todo

- [ ] Write tests for current providers, it will help with maintenance
- [ ] Update dependencies (request and DOM parsing) to work also in the browser. So if in the future we notice issues with IP banning, we could move it from backend to frontend.
- [ ] Move torrent logic to a separate package with the ability to disable it for legal reasons.
- [ ] Improve search order, not always the most relevant results are at the top
- [ ] kickass.ws provider
- [ ] rutracker.org provider
- [ ] rarbg.to provider

Ref: KiraLT/torrent-browse#1

**Comment by omgbox** [comment]
possibly omit rutracker.org provider mainly due to the reasons of audio being overlaid by russian speakers in majority of the videos.   meaning the audio can not be switched between russian or english , it is mainly english but russian audio added on top of tracker 1 as a hard copy, English users will find it very annoying.
